### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by DarioLondon** [michaelwayman/run-in-browser#1]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/Dario/.atom/packages/run-in-browser/lib/rib.coffee:6:9)
```

**Comment by michaelwayman** [comment]
Thanks for letting me know, I have fixed this now you should be able to update it from inside of atom.
