### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by finomenon** [michaelwayman/run-in-browser#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\ericf\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\ericf\.atom\packages\run-in-browser\lib\rib.coffee:6:9)
```

**Comment by finomenon** [comment]
Getting some annoying deprecation errors from this package. Please fix, asap. I don't know what this Deprecation Cop will do. He looks trigger happy.

**Comment by hesham8** [comment]
@finomenon I can take a look at it later today.

**Comment by finomenon** [comment]
awesome, thanks @hesham8 !
you can infer from error output, but just to be clear, I'm using Atom 0.177.0

**Comment by michaelwayman** [comment]
sorry about the delay guys. I updated the package, you should be able to update it now from atom and it will fix the deprecated calls.

**Comment by hesham8** [comment]
Damn it Wayman, I was gonna fix that.

**Comment by finomenon** [comment]
Nice, thanks both of you! :)
